language: generic

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - APP_NAME=markette

install: docker-compose build markette-test

script:
  - docker-compose run --rm markette-test sh -c 'flake8 && isort --recursive --check-only --diff markette'
  - docker-compose run --rm markette-test
