version: '2'
services:

  # Python base app
  skol-base:
    container_name: skol-base
    build: .
    environment:
      DATABASE_DSN: postgresql://postgres:postgres@db:5432/postgres
      ENV: dev
      LOG_LEVEL: INFO


  # ---------------------------------------------
  # Services for dev / prod.
  # ---------------------------------------------

  # Python app
  skol:
    image: tunedmystic/skol
    container_name: skol
    extends: skol-base
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/usr/src
    depends_on:
      - db

  # Postgres database
  db:
    image: postgres:11-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  # ---------------------------------------------
  # Services for testing.
  # ---------------------------------------------

  # Python test app
  skol-test:
    image: tunedmystic/skol-test
    container_name: skol-test
    extends: skol-base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=test
    volumes:
      - ${PWD}:/usr/src
    depends_on:
      - db
