version: '2'
services:

  # Python base app
  markette-base:
    container_name: markette-base
    build: .
    environment:
      DATABASE_DSN: postgresql://postgres:postgres@db:5432/postgres
      ENV: dev
      LOG_LEVEL: INFO


  # ---------------------------------------------
  # Services for dev / prod.
  # ---------------------------------------------

  # Python app
  markette:
    image: tunedmystic/markette
    container_name: markette
    extends: markette-base
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/app
    depends_on:
      - db
    tty: true
    command: [
      "uvicorn",
      "--host", "0.0.0.0", "--port", "8000",
      "--reload", "--reload-dir=/app/markette",
      "markette.app:app"
    ]

  # Postgres database
  db:
    image: postgres:11-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  # ---------------------------------------------
  # Services for testing.
  # ---------------------------------------------

  # Python test app
  markette-test:
    image: tunedmystic/markette-test
    container_name: markette-test
    extends: markette-base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA_REQUIREMENTS=requirements-dev.txt
    volumes:
      - ${PWD}:/app
    depends_on:
      - db
    environment:
      ENV: test
    command: ["pytest", "tests"]
